// <auto-generated />
using EFTest;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;

namespace EFTest.Migrations
{
    [DbContext(typeof(FilmStDBContext))]
    partial class FilmStDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026");

            modelBuilder.Entity("EFTest.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("Password");

                    b.Property<string>("RoomName");

                    b.HasKey("Id");

                    b.HasIndex("RoomName");

                    b.ToTable("ApplicationUsers");
                });

            modelBuilder.Entity("EFTest.Room", b =>
                {
                    b.Property<string>("RoomName")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("RoomPassword");

                    b.HasKey("RoomName");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("EFTest.Track", b =>
                {
                    b.Property<int>("TrackName")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Album");

                    b.Property<string>("AudioChanels");

                    b.Property<string>("Author");

                    b.Property<string>("Bitrate");

                    b.Property<string>("Bits");

                    b.Property<int>("FileSize");

                    b.Property<string>("Genre");

                    b.Property<string>("Group");

                    b.Property<string>("Length");

                    b.Property<string>("RoomName");

                    b.Property<string>("Year");

                    b.HasKey("TrackName");

                    b.HasIndex("RoomName");

                    b.ToTable("Traks");
                });

            modelBuilder.Entity("EFTest.ApplicationUser", b =>
                {
                    b.HasOne("EFTest.Room")
                        .WithMany("UsersInRoom")
                        .HasForeignKey("RoomName");
                });

            modelBuilder.Entity("EFTest.Track", b =>
                {
                    b.HasOne("EFTest.Room")
                        .WithMany("TracksInRoom")
                        .HasForeignKey("RoomName");
                });
#pragma warning restore 612, 618
        }
    }
}
